AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.java.test::aws-serverless-sample1
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  AwsServerlessSample1Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.java.test.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/aws-serverless-sample1-0.0.1-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  AwsServerlessSample1Api:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: AwsServerlessSample1Api
